const DocumentProcessingStatus = {
    STATUS_PROCESSING: 'STATUS_PROCESSING',
    STATUS_FINISHED: 'STATUS_FINISHED',
    STATUS_ERROR_UNKNOWN: 'STATUS_ERROR_UNKNOWN',
    STATUS_ERROR_CONNECTION: 'STATUS_ERROR_CONNECTION',
    STATUS_DEFAULT: 'STATUS_DEFAULT'
}
